### ISSUE TITLE
Date/timeformat is incorrect

### ISSUE THREAD

**Issue by leonfranken** [uhaciogullari/SimpleMvcSitemap#37] opened 2019-11-15 08:44 UTC
Hello Ufuk,

The date/timeformat for the "lastmod"-tag is incorrect.
The current implementation outputs "2019-11-15T09:40:00".
This should be a date "2019-11-15" or a datetime with a timezone "2019-11-15T09:40:00Z".
The timezone (in the example the "Z") is missing in the current version of the package!

Also take a look at these webpages:
[https://www.w3.org/TR/NOTE-datetime](https://www.w3.org/TR/NOTE-datetime)
[https://www.sitemaps.org/protocol.html](https://www.sitemaps.org/protocol.html)

Can you fix this in the next version?

Kind regards,
Leon

**Comment by uhaciogullari** [comment] 2019-11-15 10:55
Duplicate of #16

**Closed by uhaciogullari** 2019-11-15 10:55 UTC
